name: nRF52840 DFU Flasher (headless)
slug: nrf52840_dfu_flasher
version: "0.2.3"
description: One-shot flasher for Nordic nRF52840 USB Dongle (PCA10059) via USB DFU using nrfutil.
url: https://github.com/ArthFink/nrf52840_flasher
arch:
  - aarch64
  - amd64
  - armv7
init: false
startup: once        # one-time run; add-on stops after flashing
boot: manual
ingress: false
panel_icon: mdi:chip
stage: experimental

devices:
  - /dev/ttyACM0
  - /dev/ttyACM1
  - /dev/ttyUSB0
  - /dev/ttyUSB1
map:
  - share:rw
apparmor: false

options:
  device: "/dev/ttyACM0"        # recommend using /dev/serial/by-id/...
  baudrate: 115200              # 57600 | 115200 | 230400 | 460800 | 921600
  flow_control: false
  firmware_source: "github:ArthFink/nrf52840-OpenThread@latest"  # DFU .zip
  dry_run: false
  verbose: true
schema:
  device: device(subsystem=tty)?
  baudrate: list(57600|115200|230400|460800|921600)
  flow_control: bool?
  firmware_source: str?
  dry_run: bool?
  verbose: bool?
